spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        register: true
  profiles:
     active: native
  application:
      name: ou-config-service

server:
  port: 8888

