spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native
#  application:
#      name: micro-config-service
#  security:
#    user:
#      password: ${CONFIG_SERVICE_PASSWORD}

server:
  port: 8888

