
spring:
  application:
    name: micro-security-service # ==> This is Service-Id

---
# Items that apply to ALL profiles:
eureka:
  instance:
    appname: micro-security-service
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
server:
  port: 9100


