
spring:
  application:
    name: micro-gateway-service # ==> This is Service-Id

---
# Items that apply to ALL profiles:
eureka:
  instance:
    appname: micro-gateway-service
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
server:
  port: 8500

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  routes:

    micro-security-service:
      path: /security/**
      serviceId: micro-security-service

    micro-prototyp-app:
      path: /prototyp/**
      serviceId: micro-prototyp-app

    micro-frontend-app:
      path: /frontend/**
      serviceId: micro-frontend-app


security:
  oauth2:
    client:
      clientId: micro-gateway-service
      clientSecret: micro-gateway
      accessTokenUri: http://localhost:9100/token
      userAuthorizationUri: http://localhost:9100/auth
      scope: server
    resource:
      user-info-uri: http://localhost:9100/users/current