spring:
  application:
    name: ABC-SERVICE # ==> This is Service-Id


---
# Items that apply to ALL profiles:
eureka:
  instance:
    appname: PROTOTYPE-APP
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
server:
  port: 8000