
spring:
  application:
    name: micro-prototyp-app # ==> This is Service-Id

---
# Items that apply to ALL profiles:
eureka:
  instance:
    appname: micro-prototyp-app
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
server:
  port: 8000
