
spring:
  application:
    name: micro-gateway-service # ==> This is Service-Id

---
# Items that apply to ALL profiles:
eureka:
  instance:
    appname: micro-gateway-service
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
server:
  port: 9600

zuul:
  ignoredServices: '*'
  routes:
    micro-prototyp-app:
      path: /prototyp/**
      serviceId: micro-prototyp-app
      stripPrefix: false
      sensitiveHeaders: